### PR TITLE
Display the method return value when stepping out

### PR DESCRIPTION
**Pull request by testforstephen**
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

Close microsoft/vscode-java-debug#660

### CODE REVIEW

**Comment by testforstephen** [comment]
image

**Comment by jdneo** [comment]
What if the method has parameters? And what will it looks like when it's a invocation chain (like stream invocation)

**Comment by Eskibear** [comment]
With this icon '⎯►', then why you still need to append "returned", for better clarification?

**Comment by testforstephen** [comment]
Addressed, below is the new look.
image

**Pull request merged**
